### PR TITLE
Update to valid SPDX license format

### PR DESCRIPTION
**Pull request by stramel**

### CODE REVIEW

**Comment by fantapop** [comment]
+1

**Comment by stramel** [comment]
@deoxxa Bump

**Comment by stramel** [comment]
@deoxxa Ping

**Comment by stramel** [comment]
@deoxxa Ping

**Comment by stramel** [comment]
@deoxxa Friendly Ping

**Comment by stramel** [comment]
Ping @deoxxa

**Comment by stramel** [comment]
@deoxxa Ping

**Comment by stramel** [comment]
@deoxxa Ping

**Comment by stramel** [comment]
@deoxxa Ping

**Pull request merged**
