### PR TITLE
Callback on each item in search

### PR DESCRIPTION
**Pull request by AshKyd**
My use case: I'd like to delete a bunch of values using the search syntax.

This change:

* Adds an optional `action` argument to the `search` function, which gets called each time a key is matched.
* Adds a `removeSearch` function with the same signature as the `remove` function, which delegates to `search` with a function to delete each match.
* Tests and misc.

This doesn't break existing tests, and could potentially be extended further to add a corresponding `putSearch` method. 

Also, wasn't sure how your `docs/` folder is generated, let me know and I'll look into that too.

### CODE REVIEW

**Comment by miketheprogrammer** [comment]
I'll try to test and review as soon as possible

**Comment by AshKyd** [comment]
Thanks. Let me know if there's anything you need from me. :)

**Comment by miketheprogrammer** [comment]
Looks good, and since I dont think deoxxa will have an opinion merging.

> dotty@0.0.2 test /Users/mhernandez/miner/dotty
> vows

········ ········ ······ ······ ··············· ··········································  
  ✓ OK » 85 honored (0.033s)

**Comment by AshKyd** [comment]
Thanks a bunch for that. I'm guessing you don't have access to publish this one to NPM, should I ping deoxxa? :)

**Comment by miketheprogrammer** [comment]
He probably won't respond

**Comment by deoxxa** [comment]
Hello! Should I add someone on npm?

**Comment by miketheprogrammer** [comment]
Yea me. I'm a github maintainer

**Comment by deoxxa** [comment]
It appears you're already an owner on NPM - is it not working for you?

**Comment by miketheprogrammer** [comment]
Oh I didn't know that. Okay cool I'll make sure to publish

**Pull request merged**
